# Generated by Django 4.2.1 on 2023-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("codigo_maquina", models.CharField(max_length=100)),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("enabled", models.BooleanField()),
            ],
        ),
    ]
